name: knight_pdf
description: Premium All-in-One PDF Tool.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0' # Ensuring modern Dart

dependencies:
  flutter:
    sdk: flutter

  # --- Architecture & UI ---
  provider: ^6.1.1 # State Management
  go_router: ^13.2.0 # Navigation
  google_fonts: ^6.1.0 # Nice fonts
  flutter_svg: ^2.0.9 # For high quality icons
  cupertino_icons: ^1.0.6

  # --- Core PDF & Files ---
  pdf: ^3.11.0 # Creating PDFs
  path_provider: ^2.1.2 # Finding where to save files
  file_picker: ^8.0.0 # Picking existing PDFs/Excels
  open_filex: ^4.4.0 # Opening files externally (fallback)
  share_plus: ^9.0.0 # Sharing files
  intl: ^0.19.0 # Date formatting

  # --- Images & Manipulation ---
  image_picker: ^1.0.7 # Camera/Gallery
  image_cropper: ^11.0.0 # Cropping UI
  image: ^4.1.7 # Low level image manipulation (filters/rotate)
  excel: ^4.0.2
  # --- Specific Converters (Will add more later as needed) ---
  # We will add Excel/OCR packages in their respective parts to keep build light initially.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # Enable generation of assets if we add custom icons later
  assets:
  # - assets/images/